import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getCurrentUser } from '@/lib/auth';
import { z } from 'zod';
const updateSchema = z.object({ title: z.string().trim().min(1).max(200).optional(), description: z.string().max(5000).nullable().optional(), category: z.string().trim().min(1).max(60).optional(), priority: z.enum(['LOW','MEDIUM','HIGH','URGENT']).optional(), status: z.enum(['PENDING','IN_PROGRESS','COMPLETED','OVERDUE']).optional(), dueDate: z.coerce.date().optional(), reminderDateTime: z.coerce.date().nullable().optional() });
async function owned(id: string) { const user = await getCurrentUser(); if (!user) return { user: null, task: null }; return { user, task: await prisma.task.findFirst({ where: { id, userId: user.id } }) }; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const { user, task } = await owned(id); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!task) return NextResponse.json({ error: 'Task not found' }, { status: 404 }); return NextResponse.json({ task }); }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const { user, task } = await owned(id); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!task) return NextResponse.json({ error: 'Task not found' }, { status: 404 }); try { const data = updateSchema.parse(await request.json()); if (data.reminderDateTime && data.dueDate && data.reminderDateTime > data.dueDate) return NextResponse.json({ error: 'Reminder must be before the due date.' }, { status: 400 }); const updated = await prisma.task.update({ where: { id }, data: { ...data, ...(data.status === 'COMPLETED' ? { completedAt: new Date() } : {}) } }); return NextResponse.json({ task: updated }); } catch { return NextResponse.json({ error: 'Invalid task update.' }, { status: 400 }); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const { user, task } = await owned(id); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!task) return NextResponse.json({ error: 'Task not found' }, { status: 404 }); await prisma.task.delete({ where: { id } }); return NextResponse.json({ ok: true }); }
